### ISSUE TITLE
The RPC server is unavailable.

### ISSUE THREAD

**Issue by lisicn** [mitre/adversary#10]
Hello,
 I like this project very much. I don't know how to solve this problem. I hope you can help me.
 look at it
-----------
![01](https://user-images.githubusercontent.com/38556416/46776893-28264d80-cd40-11e8-813d-0c1215c17d9c.png)
-----------
![02](https://user-images.githubusercontent.com/38556416/46777209-52c4d600-cd41-11e8-8fa2-35892b341461.png)

1. As you can see, I opened the RPC service, but I still couldn't perform this operation.

2. Another problem is that my server uses redhunter, which prompts when I load pstools that the permissions aren't enough, and I've tried to modify the permissions, but it doesn't work.

3. If there is a systemic language problem, I think I was wrong from the beginning.

Look forward to your reply

**Comment by cl-mitre** [comment]
Alright, let's see what we have here.

1) The RPC connection might be blocked via your firewall,  which would return this error. The other quick things to check would be to verify that the account you're trying to use (topsec\guestuserx01) has the necessary permissions for WMI queries (wbemtest can help diagnose this), and to double check that you can hit the target machine from the host (can win8x05 reach win8x06?). If none of these work, let me know, and I'll try to troubleshoot further.
2) I'm not familiar with "redhunter". If you're referring to the RedHunt OS, I would try running the entire server as ROOT if you aren't already, since loading pstools requires saving a file to a directory. If that does work, it's something permissions wise, if not, more troubleshooting will be necessary. If "redhunter" is something else, you might want to try to disable it temporarily or tell it to ignore a specific directory (the one you run Caldera from).
3) I'm not quite sure what you are referring to here as a systemic language problem, so I can't comment.

Hope this helps some!

**Comment by ArtificialErmine** [comment]
If this issue still exists after upgrading to the most recent version of Caldera, feel free to re-open this issue or create a new one. Until then, this issue is being closed due to lack of activity.
