### ISSUE TITLE
 Enumerating all computers in the domain fails

### ISSUE THREAD

**Issue by thibc4** [mitre/adversary#15]
Hello, 

The problem I encountered is that the **get_computers step** fails from time to time, and thus prevents the execution of the following attacks.

Here is a screenshot of the situation: 

![get_domain - copy](https://user-images.githubusercontent.com/26906367/40169760-02e9d57e-59c7-11e8-9691-676726d54b8f.PNG)

Configuration of the environment:
- CALDERA is installed in Ubuntu 16.04 LTS 
- Domain with 2 DCs (Windows Server 2016) and 2 Workstations (Windows 10), caldera installed on all of them
- The starting victim is a workstation, and the Rat is started as a domain user.

**Comment by thibc4** [comment]
Hi @hf-mitre, thank you for your quick reply. 
I also have a hard time to reproduce it, but yes the Domain Controllers are up when it happens. I didn't check if the workstations could reach the DCs though, I will check it out next time this issue appears.

**Comment by ArtificialErmine** [comment]
Unfortunately, we don't have any blog posts or easily accessible resources providing guides on how to build out an network environment. That being said, if the issue is due to configuration of the actual target hosts themselves, try running the softening script as detailed in the readme (https://github.com/mitre/adversary/blob/master/README.md) for the most recent version of Caldera's adversary mode. If the issue still persists after trying the script and upgrading to the newest iteration of Caldera, feel free to open a new issue, or use the virtual network included.
