### ISSUE TITLE
GetLocalProfiles hangs

### ISSUE THREAD

**Issue by JimmyAstle** [mitre/adversary#17]
In running some tests the "Enumerating user profiles" steps hangs and never returns. In looking through the source the action looks to be executing fine but never returns the results. The StdOut from the step looks good and the correct user,sid information is displayed. I have a feeling something is hanging that ```await``` task.  

My Test Env information:
DC - Win2012R2
2 Member Clients - Win10 Enterprise x64 (10.0.14393 N/A Build 14393)

Im leveraging this issue as an opportunity to learn the code base and dig into logging an whatnot so any information you are willing to share to help troubleshoot would be awesome. I have put in a false command-line parameter to reg query in the source and was able to get this task to fail and then eventually continue but Im stuck in trying to fix this.

Thanks and keep up the awesome work!

**Comment by ArtificialErmine** [comment]
This issue occurred with a fairly out of date (at this point, not at the time) version of Caldera. If the problem occurs again after upgrading to the most recent version of Caldera and adversary mode, feel free to re-open the issue or create a new one, and we can investigate the parsing system further, as that is likely the culprit behind this issue. In the mean time, the issue is being closed due to lack of activity.
