### ISSUE TITLE
Lateral movement stops at Domain Controller

### ISSUE THREAD

**Issue by forensic65x** [mitre/adversary#19]
i'm using the environment provided by the DeceptionLab Github project. The network is a Windows 10 workstation, Windows 2016 Server and Windows 2016 Domain Controller.   

hxxps://github.com/clong/DetectionLab

Each operation I have attempted has compromised the starting host, and then the domain controller, but stops there.

I have a domain admin account logged in to each system during the operation.  I made sure the UseLogonCredential reg value is set to 1 to ensure both hashes and clear text passwords are available in memory.

I have tried setting starting user to both System and Active User.

My Adversary includes the 7 steps outlined in the Caldera Youtube video which shows all systems in the network getting compromised - hxxps://www.youtube.com/watch?v=xjDrWStR68E

- copy_files
- get_creds
- get_admin
- get-computers
- get-domain
- net-use
- remote-process

It's not clear why it can jump from the Win10 or Win2016 system to the DC but not the DC to the other system.

**Comment by ArtificialErmine** [comment]
adamsh25, although we don't currently have any plans to directly increase the collection of steps available to Adversary mode, if you want such functionality, feel free to create a pull request and we'll get it into the repository. In the mean time, this issue is being closed due to the original problem being resolved.
