### ISSUE TITLE
Get_domain failed

### ISSUE THREAD

**Issue by AngryOnigiri** [mitre/adversary#48]
Hello, 

I've been using the old caldera version 0.3.0 have the following issue:

```
WARNING:app.operation.operation:Failed to parse with error: 'Result is not well formed:     
Ethernet:
Knoten-IP-Adresse: [10.0.2.9] Bereichskennung: []

                Lokale NetBIOS-Namentabelle

       Name               Typ          Status
    ---------------------------------------------
    DOMAINUSER1    <00>  EINDEUTIG   Registriert 
    NEWDOMAIN      <00>  GRUPPE      Registriert 
    DOMAINUSER1    <20>  EINDEUTIG   Registriert 
'
INFO:app.operation.operation:Returned from get_domain

```

![caldera](https://user-images.githubusercontent.com/50779286/62220543-7e887980-b3b0-11e9-9bab-47f5deb03164.PNG)

Is it because my system language is in german? 

The RAT is running on a win10 domainuser (domain admin).
I've started the operation with an existing RAT and also bootstrap RAT as active user (domain admin).

**Comment by AngryOnigiri** [comment]
yes that fixed it, thank you! :) 
I changed the system language to english to avoid similar issues.
The operations seem to work fine, but some steps don't get executed (xcopy, WMI etc..), the steps are included in the adversary. I also tested the build-in adversaries...

 Is there any possibility to change/modify that?

**Comment by ArtificialErmine** [comment]
Unfortunately, since Caldera's "thing" is that it utilizes a planning algorithm to determine what steps to take, sometimes steps don't get run. In this case, I suspect that the reason xcopy and WMI aren't being used is mainly due to their functionality being provided by other steps (copy, for example). The planner doesn't see a reason to do similar actions that result in the same outcome twice, so it only runs the first one it comes across. Try removing the alternative steps and see if that helps.

**Comment by ArtificialErmine** [comment]
@AngryOnigiri The original issue appears to have been fixed here, so I'm going to close this ticket. If the "steps not being executed" issue persists after my subsequent suggestion, feel free to reopen this ticket or create a new one, and we can dig into it further.
