### ISSUE TITLE
Adding Scripts Not Showing Up?

### ISSUE THREAD

**Issue by ms08067** [mitre/adversary#9]
Running Caldera Server on Ubuntu 16. Downloaded an external powershell script and attempted to encode using encode.py. Seems to execute just fine. I move it to the folder that contains the scripts however it does not show up in the script editor. It does not appear that it 'knows' about the 'imported' or 'added' script.

**Comment by ArtificialErmine** [comment]
tdrlocal, it appears that your environment defaults to python 2 when running python, rather than the python 3 required by that script. Either way, this functionality is no longer supported by the most recent version of Caldera due to the development of Chain mode. If this general functionality is needed within Adversary mode, feel free to create an implementation and create a pull request, otherwise, it likely won't make a return anytime soon. 

In the mean time, I'm closing this ticket due to inactivity, and the initial issue being solved.
